[package]
name = "mock_trans"
version = "0.1.0"
authors = ["daiymgyl"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdma-sys = "0.3.0"
errno = "0.3.8"

[dependencies.libc]
version = "0.2"